import { useEffect, useState } from "react";
import { Alert, AppShell, Button, Group, MantineProvider, Paper, Select, Tabs, Text, TextInput, Title } from "@mantine/core";
import { IconCalendar, IconCompass, IconHome, IconLibrary, IconSearch } from "@tabler/icons-react";

type Tab = "watch" | "search" | "feed" | "library";
type Theme = "system" | "light" | "dark";
export function App() {
  const [tab, setTab] = useState<Tab>("watch"); const [theme, setTheme] = useState<Theme>(() => (localStorage.getItem("visto-theme") as Theme) || "system"); const [online, setOnline] = useState(navigator.onLine);
  useEffect(() => { localStorage.setItem("visto-theme", theme); }, [theme]); useEffect(() => { const update = () => setOnline(navigator.onLine); addEventListener("online", update); addEventListener("offline", update); return () => { removeEventListener("online", update); removeEventListener("offline", update); }; }, []);
  const nav = (value: Tab, label: string, Icon: typeof IconHome) => <Button variant={tab === value ? "light" : "subtle"} leftSection={<Icon size={18} />} onClick={() => setTab(value)}>{label}</Button>;
  return <MantineProvider defaultColorScheme={theme === "system" ? "auto" : theme}><AppShell header={{ height: 64 }} footer={{ height: 70 }} padding="md"><AppShell.Header><Group h="100%" px="md" justify="space-between"><Title order={2}>Visto</Title><Select aria-label="Theme" value={theme} onChange={value => setTheme((value || "system") as Theme)} data={[{ value: "system", label: "System theme" }, { value: "light", label: "Light" }, { value: "dark", label: "Dark" }]} w={150} /></Group></AppShell.Header><AppShell.Main>{!online && <Alert color="yellow" mb="md">You are offline. Cached information may be out of date.</Alert>}{tab === "watch" && <Watch />}{tab === "search" && <Search />}{tab === "feed" && <Feed />}{tab === "library" && <Library />}</AppShell.Main><AppShell.Footer><Group justify="space-around" h="100%">{nav("watch", "Watch", IconHome)}{nav("search", "Search", IconSearch)}{nav("feed", "Feed", IconCompass)}{nav("library", "Library", IconLibrary)}</Group></AppShell.Footer></AppShell></MantineProvider>;
}
function Watch() { const [view, setView] = useState("now"); return <><Tabs value={view} onChange={value => setView(value || "now")}><Tabs.List><Tabs.Tab value="now">Now</Tabs.Tab><Tabs.Tab value="calendar" leftSection={<IconCalendar size={16} />}>Calendar</Tabs.Tab></Tabs.List></Tabs><Title order={1} mt="xl">{view === "now" ? "Keep watching" : "Upcoming episodes"}</Title><Empty title={view === "now" ? "Nothing to continue yet" : "No upcoming episodes"} description="Add shows from Search to start tracking." /></> }
function Search() { return <><Title order={1}>Search</Title><TextInput mt="md" label="Search TMDB" placeholder="Movies and TV shows" leftSection={<IconSearch size={16} />} /><Empty title="Search TMDB" description="Search results will appear here." /></> }
function Feed() { return <><Title order={1}>Family feed</Title><Empty title="No shared activity yet" description="Activity appears here when a family member enables instance sharing." /></> }
function Library() { return <><Title order={1}>Library</Title><Empty title="Your library is empty" description="Add movies and shows from Search. Your profile and settings live here too." /><Button mt="md">Profile & settings</Button></> }
function Empty({ title, description }: { title: string; description: string }) { return <Paper withBorder p="xl" mt="md" radius="md" ta="center"><Text fw={700}>{title}</Text><Text c="dimmed">{description}</Text></Paper>; }
