package mcp

const oauthLoginPage = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Connect Visto</title>
<style>body{font:16px Inter,ui-sans-serif,system-ui,sans-serif;background:#10141a;color:#f4f4f5;display:grid;place-items:center;min-height:100vh;margin:0}.panel{box-sizing:border-box;width:min(440px,calc(100% - 32px));padding:28px;border:1px solid #3b3e46;border-radius:16px;background:#1b1e26;box-shadow:0 24px 70px rgb(0 0 0 / .35)}h1{margin:0 0 8px;font-size:1.9rem;letter-spacing:-.045em}p{color:#b7bac3;line-height:1.5}.account{margin-top:18px}.account strong{color:#f4f4f5}.scope{padding:10px 0;border-top:1px solid #393c44}.scope label{display:flex;align-items:flex-start;gap:9px;line-height:1.45}.scope input{margin:4px 0 0;accent-color:#f2b544}.actions{display:flex;gap:10px;margin-top:22px}.actions button{min-height:42px;padding:10px 18px;border:0;border-radius:10px;background:#f2b544;color:#1b1e26;font-weight:700;cursor:pointer}.actions .cancel{background:#383b43;color:#fff}.error{color:#ff9898}</style>
<main class="panel"><img src="/icon.svg?v=2" width="44" height="44" alt="" style="display:block;border-radius:14px;margin-bottom:20px"><h1>Connect Visto</h1><p><strong>{{.ClientName}}</strong> wants permission to:</p><p class="account">Signed in as <strong>{{.UserEmail}}</strong></p>{{if .Error}}<p class="error">{{.Error}}</p>{{end}}
<form method="post" action="/oauth/authorize"><input type="hidden" name="csrf" value="{{.CSRF}}">{{range .Hidden}}<input type="hidden" name="{{.Name}}" value="{{.Value}}">{{end}}
<div class="scope"><label><input type="checkbox" name="scope" value="read" {{if .Read}}checked{{end}}> Read my Visto library, progress, and watch history</label></div>
<div class="scope"><label><input type="checkbox" name="scope" value="write" {{if .Write}}checked{{end}}> Add titles, update lists, mark media watched, and rate it</label></div>
<div class="scope"><label><input type="checkbox" name="scope" value="offline_access" {{if .Offline}}checked{{end}}> Stay connected between visits</label></div>
<div class="actions"><button name="consent" value="allow">Authorize {{.ClientName}}</button><button class="cancel" formnovalidate name="consent" value="deny">Cancel</button></div></form></main></html>`
